/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type ProbFormUpdateFormInputValues = {
    empID?: string;
    adaptability?: string;
    additionalInfo?: string;
    attention?: string;
    attitude?: string;
    commitment?: string;
    communication?: string;
    deadline?: string;
    diligent?: string;
    extensionPeriod?: string;
    gmDate?: string;
    hrDate?: string;
    hrName?: string;
    initiative?: string;
    managerDate?: string;
    managerName?: string;
    pace?: string;
    quality?: string;
    recommendation?: string;
    responsibility?: string;
    supervisorDate?: string;
    supervisorName?: string;
    teamwork?: string;
    extendProbED?: string;
    gmApproved?: string;
    managerApproved?: string;
    supervisorApproved?: string;
    communicationDetails?: string;
    qualityDetails?: string;
    paceDetails?: string;
    initiativeDetails?: string;
    attitudeDetails?: string;
    adaptabilityDetails?: string;
    teamworkDetails?: string;
    responsibilityDetails?: string;
    diligentDetails?: string;
    commitmentDetails?: string;
    probStatus?: boolean;
    gmName?: string;
};
export declare type ProbFormUpdateFormValidationValues = {
    empID?: ValidationFunction<string>;
    adaptability?: ValidationFunction<string>;
    additionalInfo?: ValidationFunction<string>;
    attention?: ValidationFunction<string>;
    attitude?: ValidationFunction<string>;
    commitment?: ValidationFunction<string>;
    communication?: ValidationFunction<string>;
    deadline?: ValidationFunction<string>;
    diligent?: ValidationFunction<string>;
    extensionPeriod?: ValidationFunction<string>;
    gmDate?: ValidationFunction<string>;
    hrDate?: ValidationFunction<string>;
    hrName?: ValidationFunction<string>;
    initiative?: ValidationFunction<string>;
    managerDate?: ValidationFunction<string>;
    managerName?: ValidationFunction<string>;
    pace?: ValidationFunction<string>;
    quality?: ValidationFunction<string>;
    recommendation?: ValidationFunction<string>;
    responsibility?: ValidationFunction<string>;
    supervisorDate?: ValidationFunction<string>;
    supervisorName?: ValidationFunction<string>;
    teamwork?: ValidationFunction<string>;
    extendProbED?: ValidationFunction<string>;
    gmApproved?: ValidationFunction<string>;
    managerApproved?: ValidationFunction<string>;
    supervisorApproved?: ValidationFunction<string>;
    communicationDetails?: ValidationFunction<string>;
    qualityDetails?: ValidationFunction<string>;
    paceDetails?: ValidationFunction<string>;
    initiativeDetails?: ValidationFunction<string>;
    attitudeDetails?: ValidationFunction<string>;
    adaptabilityDetails?: ValidationFunction<string>;
    teamworkDetails?: ValidationFunction<string>;
    responsibilityDetails?: ValidationFunction<string>;
    diligentDetails?: ValidationFunction<string>;
    commitmentDetails?: ValidationFunction<string>;
    probStatus?: ValidationFunction<boolean>;
    gmName?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type ProbFormUpdateFormOverridesProps = {
    ProbFormUpdateFormGrid?: PrimitiveOverrideProps<GridProps>;
    empID?: PrimitiveOverrideProps<TextFieldProps>;
    adaptability?: PrimitiveOverrideProps<TextFieldProps>;
    additionalInfo?: PrimitiveOverrideProps<TextFieldProps>;
    attention?: PrimitiveOverrideProps<TextFieldProps>;
    attitude?: PrimitiveOverrideProps<TextFieldProps>;
    commitment?: PrimitiveOverrideProps<TextFieldProps>;
    communication?: PrimitiveOverrideProps<TextFieldProps>;
    deadline?: PrimitiveOverrideProps<TextFieldProps>;
    diligent?: PrimitiveOverrideProps<TextFieldProps>;
    extensionPeriod?: PrimitiveOverrideProps<TextFieldProps>;
    gmDate?: PrimitiveOverrideProps<TextFieldProps>;
    hrDate?: PrimitiveOverrideProps<TextFieldProps>;
    hrName?: PrimitiveOverrideProps<TextFieldProps>;
    initiative?: PrimitiveOverrideProps<TextFieldProps>;
    managerDate?: PrimitiveOverrideProps<TextFieldProps>;
    managerName?: PrimitiveOverrideProps<TextFieldProps>;
    pace?: PrimitiveOverrideProps<TextFieldProps>;
    quality?: PrimitiveOverrideProps<TextFieldProps>;
    recommendation?: PrimitiveOverrideProps<TextFieldProps>;
    responsibility?: PrimitiveOverrideProps<TextFieldProps>;
    supervisorDate?: PrimitiveOverrideProps<TextFieldProps>;
    supervisorName?: PrimitiveOverrideProps<TextFieldProps>;
    teamwork?: PrimitiveOverrideProps<TextFieldProps>;
    extendProbED?: PrimitiveOverrideProps<TextFieldProps>;
    gmApproved?: PrimitiveOverrideProps<TextFieldProps>;
    managerApproved?: PrimitiveOverrideProps<TextFieldProps>;
    supervisorApproved?: PrimitiveOverrideProps<TextFieldProps>;
    communicationDetails?: PrimitiveOverrideProps<TextFieldProps>;
    qualityDetails?: PrimitiveOverrideProps<TextFieldProps>;
    paceDetails?: PrimitiveOverrideProps<TextFieldProps>;
    initiativeDetails?: PrimitiveOverrideProps<TextFieldProps>;
    attitudeDetails?: PrimitiveOverrideProps<TextFieldProps>;
    adaptabilityDetails?: PrimitiveOverrideProps<TextFieldProps>;
    teamworkDetails?: PrimitiveOverrideProps<TextFieldProps>;
    responsibilityDetails?: PrimitiveOverrideProps<TextFieldProps>;
    diligentDetails?: PrimitiveOverrideProps<TextFieldProps>;
    commitmentDetails?: PrimitiveOverrideProps<TextFieldProps>;
    probStatus?: PrimitiveOverrideProps<SwitchFieldProps>;
    gmName?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type ProbFormUpdateFormProps = React.PropsWithChildren<{
    overrides?: ProbFormUpdateFormOverridesProps | undefined | null;
} & {
    id?: string;
    probForm?: any;
    onSubmit?: (fields: ProbFormUpdateFormInputValues) => ProbFormUpdateFormInputValues;
    onSuccess?: (fields: ProbFormUpdateFormInputValues) => void;
    onError?: (fields: ProbFormUpdateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: ProbFormUpdateFormInputValues) => ProbFormUpdateFormInputValues;
    onValidate?: ProbFormUpdateFormValidationValues;
} & React.CSSProperties>;
export default function ProbFormUpdateForm(props: ProbFormUpdateFormProps): React.ReactElement;
